## Master App Resources 
POST http://localhost:4004/odata/v4/tool-page/MasterAppResources   
Content-Type: application/json

{
    "resourceType":"LGO",    
    "appName":"iVen(Vendor Management)",
    "mimeType":"image/jpg",   
    "name":"Nihilent.jpg"  
}  
   
